# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'DownTube' do
  pod 'XCDYouTubeKit'
  pod 'MMWormhole'
end

target 'DownTubeShareExtension' do
  pod 'MMWormhole'
end

target 'DownTubeUITests' do

end

